import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import NextAuthSessionProvider from "./provider";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "EduLaw - Learn law with your prefered learning method",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
      </body>
    </html>
  );
}
